name: Auto Assign
on:
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Auto Assign Action
      uses: kentaro-m/auto-assign-action@v2.0.0
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          addAssignees: author
          reviewers: ryugibo
