name: Auto assign pull request

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: "Auto assignee PR"
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          assignees: ryugibo
          allowSelfAssign: true
      - name: "Auto reviewer PR"
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          teams: dev
          teamIsPullRequestReviewer: true
